### ISSUE TITLE
WBT2.0 LidarInfo can't read laz file. And breaks(replace) the input file.

### ISSUE THREAD

**Issue by hiroyuki-sato** [jblindsay/whitebox-tools#209]
Hello, Developers. I found an issue with LAZ reading.

## Environment

* OS: macOS 10.12.1
* WhiteboxTools: v2.0.0
* sample data: [noaa](https://chs.coast.noaa.gov/htdata/lidar4_z/geoid12b/data/9333/20200701_376000e_1915000n.laz) just for use sample.

## Problem

* WBT 2.0 can't read a LAZ file.
* It breaks the file. After reading the file, it was replaced as an `HTML` file.

## Expect behavior

`whitebox_tools -r=lidarinfo ` generates the HTML file.

### Before reading

It's a LiDAR file.

```
file test.laz
test.laz: LIDAR point data records, version 1.4, SYSID NOAA OCM, Generating Software datum_shift (Version: v1.0-200-
```

### Reading las file.

```
RUST_BACKTRACE=full whitebox_tools -r=lidarinfo -i test.laz
****************************
* Welcome to LidarInfo     *
* Powered by WhiteboxTools *
* www.whiteboxgeo.com      *
****************************
thread 'main' panicked at 'Error reading LAZ file.: Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })', whitebox-lidar/src/las.rs:1177:61
stack backtrace:
   0:        0x10306cda4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6a8908fa3ed6f9e8
   1:        0x10308fb2c - core::fmt::write::h4be00f71c5582919
   2:        0x1030693ca - std::io::Write::write_fmt::h49e76926070788f1
   3:        0x10306ebbf - std::panicking::default_hook::{{closure}}::h1577f0656e419c0e
   4:        0x10306e6bd - std::panicking::default_hook::h1aef594179c4fd25
   5:        0x10306f2c0 - std::panicking::rust_panic_with_hook::h10bc487d002f6c42
   6:        0x10306ed65 - std::panicking::begin_panic_handler::{{closure}}::hf4cfa78c105ce648
   7:        0x10306d218 - std::sys_common::backtrace::__rust_end_short_backtrace::h1df96a166e4351c4
   8:        0x10306ecca - _rust_begin_unwind
   9:        0x1030a9def - core::panicking::panic_fmt::hea8fe6c9e0720810
  10:        0x1030a9ed5 - core::result::unwrap_failed::h58357c1be19e8a7d
  11:        0x102f05b35 - whitebox_lidar::las::LasFile::read_laz_data::h460d3565862cfd4b
  12:        0x102efb220 - whitebox_lidar::las::LasFile::read::h6f61b7b39ba968eb
  13:        0x102ef9005 - whitebox_lidar::las::LasFile::new::hc04258e00c16e1aa
  14:        0x102869c8e - <whitebox_tools::tools::lidar_analysis::lidar_info::LidarInfo as whitebox_tools::tools::WhiteboxTool>::run::h510ee86318083fbe
  15:        0x10270d7f7 - whitebox_tools::tools::ToolManager::run_tool::h51a16bd858603add
  16:        0x1028f7140 - whitebox_tools::run::h4ca69e99c6c8aa3e
  17:        0x1028f45fe - whitebox_tools::main::hbde18ed91eecadc2
  18:        0x102e27d8a - std::sys_common::backtrace::__rust_begin_short_backtrace::hf732df831d19dac3
  19:        0x10293ca4c - std::rt::lang_start::{{closure}}::hd60a66c7640d0928
  20:        0x10306f7e1 - std::rt::lang_start_internal::h4428f22d05a79c62
  21:        0x1028f8419 - _main
```

### After reading

It was replaced as an `HTML` file.

```
file test.laz
test.laz: HTML document text, ASCII text
```

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
        <head>
            <meta content="text/html; charset=UTF-8" http-equiv="content-type">
            <title>LAS File Summary</title>
            <style  type="text/css">
                h1 {
                    font-size: 14pt;
                    margin-left: 15px;
                    margin-right: 15px;
                    text-align: center;
                    font-family: Helvetica, Verdana, Geneva, Arial, sans-serif;
                }
                h2 {
                    font-size: 12pt;
                    margin-left: 15px;
                    margin-right: 15px;
                    text-align: left;
                    font-family: Helvetica, Verdana, Geneva, Arial, sans-serif;
                }
                p, ol, ul, li {
                    font-size: 12pt;
                    font-family: Helvetica, Verdana, Geneva, Arial, sans-serif;
                    margin-left: 15px;
                    margin-right: 15px;
                }
                caption {
                    font-family: Helvetica, Verdana, Geneva, Arial, sans-serif;
                    font-size: 12pt;
                    margin-left: 15px;
                    margin-right: 15px;
                }
                table {
                    font-size: 12pt;
                    font-family: Helvetica, Verdana, Geneva, Arial, sans-serif;
                    font-family: arial, sans-serif;
                    border-collapse: collapse;
                    align: center;
                }
                td, th {
                    text-align: left;
                    padding: 8px;
                }
                tr:nth-child(1) {
                    border-bottom: 1px solid #333333;
                    border-top: 2px solid #333333;
                }
                tr:last-child {
                    border-bottom: 2px solid #333333;
                }
                tr:nth-child(even) {
                    background-color: #dddddd;
                }
                .numberCell {
                    text-align: right;
                }
                .headerCell {
                    text-align: center;
                }
            </style>
        </head>
        <body>
            <h1>LAS File Summary</h1>
```

## Note

`pdal info` command works correctly.

```
{
  "file_size": 11411095,
  "filename": "test.laz",
  "now": "2021-12-10T20:26:05+0900",
  "pdal_version": "2.3.0 (git-version: Release)",
  "reader": "readers.las",
  "stats":
  {
    "bbox":
    {
      "EPSG:4326":
      {
        "bbox":
        {
          "maxx": 145.8351655,
          "maxy": 17.3170154,
          "maxz": 280.99,
          "minx": 145.8331472,
          "miny": 17.3124852,
          "minz": -61.88
        },
        "boundary": { "type": "Polygon", "coordinates": [ [ [ 145.833147200000013, 17.3124852, -61.88 ], [ 145.833147200000013, 17.3170154, -61.88 ], [ 145.835165499999988, 17.3170154, 280.99 ], [ 145.835165499999988, 17.3124852, 280.99 ], [ 145.833147200000013, 17.3124852, -61.88 ] ] ] }
      },
      "native":
      {
        "bbox":
        {
          "maxx": 145.8351655,
          "maxy": 17.3170154,
          "maxz": 280.99,
          "minx": 145.8331472,
          "miny": 17.3124852,
          "minz": -61.88
        },
        "boundary": { "type": "Polygon", "coordinates": [ [ [ 145.833147200000013, 17.3124852, -61.88 ], [ 145.833147200000013, 17.3170154, -61.88 ], [ 145.835165499999988, 17.3170154, 280.99 ], [ 145.835165499999988, 17.3124852, 280.99 ], [ 145.833147200000013, 17.3124852, -61.88 ] ] ] }
      }
    },
    "statistic":
    [
      {
        "average": 145.8340938,
        "count": 2362173,
        "maximum": 145.8351655,
        "minimum": 145.8331472,
        "name": "X",
        "position": 0,
        "stddev": 0.0004403947014,
        "variance": 1.93947493e-07
      },
      {
        "average": 17.31508243,
        "count": 2362173,
        "maximum": 17.3170154,
        "minimum": 17.3124852,
        "name": "Y",
        "position": 1,
        "stddev": 0.001287302545,
        "variance": 1.657147843e-06
      },
      {
        "average": 49.66453985,
        "count": 2362173,
        "maximum": 280.99,
        "minimum": -61.88,
        "name": "Z",
        "position": 2,
        "stddev": 10.87741901,
        "variance": 118.3182443
      },
      {
        "average": 12366.62355,
        "count": 2362173,
        "maximum": 65530,
        "minimum": 0,
        "name": "Intensity",
        "position": 3,
        "stddev": 9484.340113,
        "variance": 89952707.38
      },
      {
        "average": 1.118388873,
        "count": 2362173,
        "maximum": 4,
        "minimum": 0,
        "name": "ReturnNumber",
        "position": 4,
        "stddev": 0.3562239242,
        "variance": 0.1268954842
      },
      {
        "average": 1.221980778,
        "count": 2362173,
        "maximum": 4,
        "minimum": 0,
        "name": "NumberOfReturns",
        "position": 5,
        "stddev": 0.4870199297,
        "variance": 0.2371884119
      },
      {
        "average": 0.5004807015,
        "count": 2362173,
        "maximum": 1,
        "minimum": 0,
        "name": "ScanDirectionFlag",
        "position": 6,
        "stddev": 0.4999998748,
        "variance": 0.2499998748
      },
      {
        "average": 0.0001998160169,
        "count": 2362173,
        "maximum": 1,
        "minimum": 0,
        "name": "EdgeOfFlightLine",
        "position": 7,
        "stddev": 0.01413422,
        "variance": 0.000199776175
      },
      {
        "average": 1.514679492,
        "count": 2362173,
        "maximum": 42,
        "minimum": 1,
        "name": "Classification",
        "position": 8,
        "stddev": 1.121090262,
        "variance": 1.256843376
      },
      {
        "average": -9.707561185,
        "count": 2362173,
        "maximum": 9.774000168,
        "minimum": -19.49399948,
        "name": "ScanAngleRank",
        "position": 9,
        "stddev": 7.80958716,
        "variance": 60.98965161
      },
      {
        "average": 1.905346899,
        "count": 2362173,
        "maximum": 3,
        "minimum": 0,
        "name": "UserData",
        "position": 10,
        "stddev": 1.432687348,
        "variance": 2.052593036
      },
      {
        "average": 23032.60134,
        "count": 2362173,
        "maximum": 23040,
        "minimum": 23030,
        "name": "PointSourceId",
        "position": 11,
        "stddev": 4.387077419,
        "variance": 19.24644828
      },
      {
        "average": 277693581.4,
        "count": 2362173,
        "maximum": 277693751.4,
        "minimum": 277693516.9,
        "name": "GpsTime",
        "position": 12,
        "stddev": 98.56306821,
        "variance": 9714.678415
      },
      {
        "average": 1.905346899,
        "count": 2362173,
        "maximum": 3,
        "minimum": 0,
        "name": "ScanChannel",
        "position": 13,
        "stddev": 1.432687348,
        "variance": 2.052593036
      },
      {
        "average": 1.190447524,
        "count": 2362173,
        "maximum": 8,
        "minimum": 0,
        "name": "ClassFlags",
        "position": 14,
        "stddev": 1.925340594,
        "variance": 3.706936401
      }
    ]
  }
}
```

**Comment by hiroyuki-sato** [comment]
https://github.com/jblindsay/whitebox-tools/blob/e8b0f6e78ed98ad2ce7addf21c33b691f82c21c3/whitebox-tools-app/src/tools/lidar_analysis/lidar_info.rs#L214-L216

This part doesn't case the suffix `laz`.

**Comment by Afrancioni** [comment]
Hello, 

I wouldn't say WBT 2.0 is unable to read .laz files. This tool specifically requires a .las file as input (i.e., see manual https://www.whiteboxgeo.com/manual/wbt_book/available_tools/lidar_tools.html#LidarInfo). I am flagging this post as a feature request in which this tool can take either a .las or .laz file as input.

**Comment by hiroyuki-sato** [comment]
Hello, @Afrancioni Thank you for your reply.

I read this [release notes](https://github.com/jblindsay/whitebox-tools/releases/tag/v2.0.0)

> The most important feature in this release is the addition of support for reading and writing the LAZ compressed LiDAR format for all of the LiDAR tools in WBT.

I could read the laz file using `-o` option like `whitebox_tools -r=lidarinfo -i 20200701_376000e_1915000n.laz -o test.html`

**Comment by jblindsay** [comment]
I just tested the tool with the LAZ file that you kindly attached and did not encounter any error.

<img width="595" alt="Screen Shot 2022-01-29 at 4 18 09 PM" src="https://user-images.githubusercontent.com/8441542/151677859-5f39445d-09c4-4601-93a7-a9a93e9a2712.png">

I've also tested the LidarInfo tool with several other LAZ files that I have available and none of them threw the error that you encountered. I am therefore closing this issue as I am not able to replicate it. If you continue to experience issues, please feel free to re-open.

**Comment by hiroyuki-sato** [comment]
Hello, @jblindsay 

Thank you for your reply.

Did you try `lidarinfo` without `-o` option?
It causes the error **without** `-o` option.

```
whitebox_tools --version
WhiteboxTools v2.0.0 by Dr. John B. Lindsay (c) 2017-2021

WhiteboxTools is an advanced geospatial data analysis platform developed at
the University of Guelph's Geomorphometry and Hydrogeomatics Research
Group (GHRG). See www.whiteboxgeo.com for more details.
```

## OK: with `-o` option

```
% whitebox_tools -r=lidarinfo -i test.laz -o test.html
****************************
* Welcome to LidarInfo     *
* Powered by WhiteboxTools *
* www.whiteboxgeo.com      *
****************************
Complete! Please see test.html for output.
```

## NG: without `-o` option

```
% whitebox_tools -r=lidarinfo -i test.laz
****************************
* Welcome to LidarInfo     *
* Powered by WhiteboxTools *
* www.whiteboxgeo.com      *
****************************
thread 'main' panicked at 'Error reading LAZ file.: Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })', whitebox-lidar/src/las.rs:1177:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jblindsay** [comment]
This tool needs to be run with a specified output file. All it does is generate this file, so if you don't specify one, there isn't much for it to do. It's not unexpected behaviour for it throw an error without a specified output HTML file.

**Comment by jblindsay** [comment]
I know realize that I had set the output parameter as optional, which was my mistake. This tool truly can't be run without specifying the output file. I've just updated the code to make the -o necessary.

**Comment by hiroyuki-sato** [comment]
Hello, @jblindsay. Thank you for fixing this issue!
