### ISSUE TITLE
Watershed tool returning empty raster?

### ISSUE THREAD

**Issue by imyourbiggestphan** [jblindsay/whitebox-tools#225]
I'm relatively new to using WBT. I've completed all the steps leading up to delineating a watershed. The last step I'm able to complete is extracting streams. However, whenever I try to run the watersheed tool, it returns an empty raster with no watershed basin. 

![image](https://user-images.githubusercontent.com/99051837/152608116-c1a9a12a-3fad-46c0-ad2a-d0f61666e044.png)

I've been able to successfully run this before, so this is a new error for me.

I'm running WBT via QGIS plugins.

**Comment by Afrancioni** [comment]
Can you please expand more on your methodology? What WhiteboxTools specific tools did you use prior to using the Watershed tool? 

You mention that you used the QGIS plugin. Do you get the same result using the Python API that comes with the WBT download or the WhiteboxRunner front end?

I just ran the tool on a test dataset and I got a valid extracted Watershed raster. It could help if you post a link to your data.

**Comment by HRL-EOMAP** [comment]
I am having the same issue and cannot pinpoint exactly what is causing it. The output isn't exactly empty, it is just very small (1, 2 pixels).
My main suspicion is the pour point shapefile input:
- Whenever I create a point shapefile inside qgis and export it/just use it as a temporary layer, using both a python script and the qgis GUI, it works fine....most of the times.
- When I use a python script to create the pour point shapefile (using everything possible - geopandas, fiona, even osgeo), it doesn't work. I tried everything I could (changed the encoding for the attribute table, even the values of the attribute themselves). I tried once changing the attribute table first column name to 'FID' and the value for the point as 0 and it worked...once. Then for some reason when I tried again, it didn't work.

As for the tools I used for creating the pointer file: I downloaded the SRTM files from Earthdata (https://search.earthdata.nasa.gov/search/granules?p=C1000000240-LPDAAC_ECS&pg[0][v]=f&pg[0][gsk]=-start_date&q=srtm&fi=SRTM&as[instrument][0]=SRTM&tl=1660151053.848!3!!&lat=-0.0703125)
Then I used "BreachDepressionsLeastCost" (also tried BreachDepression and all the FillDepressions), and after that the D8 Pointer. I tried this both in python and in Qgis. With the pour point shapefile and the D8Pointer raster then I executed the watershed algorithm (again, both python and qgis).

**Comment by jblindsay** [comment]
Did you snap the pour points using either JensenSnapPourPoints or SnapPourPoints before extracting the watersheds?

**Comment by HRL-EOMAP** [comment]
> Did you snap the pour points using either JensenSnapPourPoints or SnapPourPoints before extracting the watersheds?

My apologies, I forgot to say that I did. But after you mentioned it, I went to check if the pour points were "inside" the streams and they weren't even after applying the SnapPourPoints - only then I realized that my X and Y coordinates were inverted (I got them confused since I'm working in an area where they are similar - around 40º lat and 40º long). After I fixed that, the algorithm ran flawlesly...

So yes, I think the SnapPourPoints algorithm can probably fix OP's problem.

**Comment by jblindsay** [comment]
Okay, glad it is resolved.

**Comment by mn5hk** [comment]
Hi @jblindsay, I have perhaps a similar issue. I am trying to test sub-basin dilineation with the [Hydrosheds](https://www.hydrosheds.org/hydrosheds-core-downloads) flow direction and flow accumulation dataset for the Rhine basin and it does not seem to be working as I anticipate. Here, the `pour_points` I have selected is the point with the maximum flow accumulation.

The input `flow_accum_raster` and `flow_dir_raster` have been prepared by clipping the EU-wide raster obtained from Hydrosheds with a Rhine shapefile.

The code failed to generate outputs for both `snapped_pour_point` and `watershed` dilineation.

Sharing my code below:
```python
# Initialize WhiteboxTools
wbt = whitebox.WhiteboxTools()
wbt.set_working_dir(".")
wbt.verbose = True
wbt.RUST_BACKTRACE = 1

print("Whitebox setup completed")

# Inputs
flow_accum_raster = "rhine_flowacc_15s.tif"  # flow accumulation raster
flow_dir_raster = "rhine_flowdir_3s.tif"       # Flow direction raster
pour_points = "pour_points.shp"              # Pour points (shapefile or raster), point at which flow accumulation is max
snapped_pour_points = "snapped_pour_points.shp" # Snapped Pour Points using Jensen Snap Pour Point
output_subbasin = "subbasin.tif"             # Output subbasin raster

# Step 1: Snap Pour Points
wbt.jenson_snap_pour_points(
    pour_pts=pour_points,
    streams=flow_accum_raster,
    output=snapped_pour_points,
    snap_dist=5
)

# Verify snapped pour points exist
if os.path.exists(snapped_pour_points):
    print(f"Snapped pour points saved to {snapped_pour_points}")
else:
    print("Failed to generate snapped pour points. Check inputs and parameters.")
    
# Step 2: Delineate subbasin
wbt.watershed(
    d8_pntr=flow_dir_raster,
    pour_pts=pour_points,
    output=output_subbasin
)

if os.path.exists(output_subbasin):
    print(f"Subbasin delineated and saved to {output_subbasin}")
else:
    print("Failed to generate subbasin raster. Check input files and parameters.")

```

Sharing the error message below:
```python
Whitebox setup completed
./whitebox_tools --run="JensonSnapPourPoints" --wd="." --pour_pts='pour_points.shp' --streams='rhine_flowacc_15s.tif' --output='snapped_pour_points.shp' --snap_dist='5' -v --compress_rasters=False

***********************************
* Welcome to JensonSnapPourPoints *
* Powered by WhiteboxTools        *
* [www.whiteboxgeo.com](https://www.whiteboxgeo.com/)             *
***********************************
Reading data...
thread 'main' panicked at whitebox-vector/src/shapefile/mod.rs:238:56:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Failed to generate snapped pour points. Check inputs and parameters.
./whitebox_tools --run="Watershed" --wd="." --d8_pntr='rhine_flowdir_3s.tif' --pour_pts='pour_points.shp' --output='subbasin.tif' -v --compress_rasters=False

****************************
* Welcome to Watershed     *
* Powered by WhiteboxTools *
* [www.whiteboxgeo.com](https://www.whiteboxgeo.com/)      *
****************************
Reading data...
thread 'main' panicked at whitebox-tools-app/src/main.rs:72:21:
No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Failed to generate subbasin raster. Check input files and parameters.
```

Also, sharing plots of my flow accumulation and flow direction rasters with pour points:
![image](https://github.com/user-attachments/assets/c861b2fd-31aa-493b-8b32-4aa4705debc8)
