### ISSUE TITLE
Whitebox tools for QGIS plugin error in new version

### ISSUE THREAD

**Issue by frnmz** [jblindsay/whitebox-tools#242]
Hi, thanks for the great software!
But the latest version of Whitebox tools plugin (1.03) for QGIS have a problem every time I installed it:
Couldn't load plugin 'wbt_for_qgis' 
```

ModuleNotFoundError: No module named 'processing_wbt' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Farhan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wbt_for_qgis\__init__.py", line 25, in 
    from wbt_for_qgis.plugin import WbtPlugin
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Farhan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wbt_for_qgis\plugin.py", line 30, in 
    from wbt_for_qgis.wbtprovider import WbtProvider
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Farhan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wbt_for_qgis\wbtprovider.py", line 34, in 
    from processing_wbt.wbtalgorithm import WbtAlgorithm
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'processing_wbt'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.24.2-Tisler Tisler, 13c1a028 

Python Path:
C:\Users/Farhan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\road_slope_calculator
C:/OSGeo4W/apps/qgis/./python
C:/Users/Farhan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Farhan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\GDAL-3.4.2-py3.9-win-amd64.egg
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Farhan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Farhan\AppData\Local\acatama\python39
C:\Users\Farhan\AppData\Local\acatama\python39\lib\site-packages
```

The problem did not happen in 1.0.2 as I already tried downgrading it.

**Comment by jblindsay** [comment]
@frnmz I do so apologize, I thought that I had fixed this particular problem and I see now that I regressed it with v1.0.3. I'll update this immediately to fix the issue. Unfortunately, however, the plugin approval process on the QGIS side of things often takes quite a few days. Thank you for reporting the issue.
