### ISSUE TITLE
Error on plugin load - version 1.04

### ISSUE THREAD

**Issue by Alickop** [jblindsay/whitebox-tools#243]
TypeError: object of type 'NoneType' has no len() 
Traceback (most recent call last):
  File "C:\Users/Alick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wbt_for_qgis\wbtprovider.py", line 88, in loadAlgorithms
    wbtdescriptions.createDescriptions()
  File "C:\Users/Alick/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wbt_for_qgis\wbtdescriptions.py", line 90, in createDescriptions
    if len(tools) > num_description_files:
TypeError: object of type 'NoneType' has no len()

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.6-Białowieża Białowieża, b6f33b1a

**Comment by Afrancioni** [comment]
Hello, 

We are aware of the issue and working on a fix. However , the plugin approval process on the QGIS side of things often takes quite a few days and so the fix may not be available for a little while. You can revert back to 1.0.2 if you prefer or you can access the WBT through other front ends (such as WhiteboxRunner). Thank you for reporting the issue and we hope to get a fix available soon.
