### ISSUE TITLE
thread 'main' panicked at 'The file does not currently contain any record data.', whitebox-tools-app\src\main.rs:72:21

### ISSUE THREAD

**Issue by Bibiisneaks** [jblindsay/whitebox-tools#263]
Hello,

I have issues running the LidarRooftopAnalysis tool in python, and I don't get where the issue come from.

Error is :
thread 'main' panicked at 'The file does not currently contain any record data.', whitebox-tools-app\src\main.rs:72:21'''

When I use the same inputs data (lidar and polygon) in qgis I have no issues, which makes me think after reading older issues that it might be due to the shapefile reader used in the .exe file

I can provide the input data if necessary.

Thanks in advance

**Comment by Bibiisneaks** [comment]
Thanks for quick answering, here is a download link for the files (as the lidar file is too heavy to upload on git)

https://we.tl/t-EW0L7WPA5P

Let me know if you need anything else

**Comment by Bibiisneaks** [comment]
Hello again, did you have time to check at this issue ? Or to try with the provided files to see if you had the same errors ?
Thanks

**Comment by dubing-bit** [comment]
I ran into the same problem using the CLump tool, reading and writing TIF images

**Comment by dubing-bit** [comment]
> 
Have you solved this problem

**Comment by ohusiev** [comment]
Hello, I have also encountered the same problem with the LidarRooftopAnalysis tool but Running it from QGIS. @Bibiisneaks @jblindsay  I wonder if you could trace back and suggest a solution, please? if there were any. Thank you in advance

**Comment by Anders-Hopkins** [comment]
@jblindsay I am having this error while trying to use the RasterStreamtoVector tool. I am able to successfully run this tool with a smaller sample of my gridded data, but it fails when I try with my larger datasets. So the problem must be with my input gridded data rather than the environment or the toolset. I am using ESRI's flow directions for my pointer grid, and I specify this in the function inputs. Originally, I was getting another error (thread 'main' panicked at 'An unexpected value has been identified in the pointer image. This tool requires a pointer grid that has been created using either the D8 or Rho8 tools.', whitebox-tools-app/src/main.rs:72:21) but I was able to get past this by running the SetNodataValue tool. I'm wondering if this 'no record data' error is being cause by missing or unexpected metadata for the input gridded datasets.
