### ISSUE TITLE
LidarTINGridding kernel panic

### ISSUE THREAD

**Issue by jfprieur** [jblindsay/whitebox-tools#36]
Hello, I am getting these errors when running the following code, which works on other lidar datasets I have. The process continues for a few more tiles with this message interspersed with the progress messages and then the program hangs with no output.

Any idea where I can start troubleshooting these lidar tiles? Thank you. I tried resolution of 5m but same issues.

`wbt.lidar_tin_gridding(
parameter="elevation", 
returns="all", 
resolution=0.25, 
exclude_cls='0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18')`

> >Progress: 5%
> >Finished interpolating \\\374000_5141000_suffix (9 of 138)
> >Finished interpolating \\\375000_5143000_suffix (10 of 138)
> >Progress: 6%
> >thread 'unnamed' panicked at 'index out of bounds: the len is 604504064 but the index is 604504064',/rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\src\libcore\slice\mod.rs:2463:10
> >note: Run with `RUST_BACKTRACE=1` for a backtrace.
> >thread 'unnamed' panicked at 'index out of bounds: the len is 604504064 but the index is 604504064',/rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\src\libcore\slice\mod.rs:2463:10
> >Finished interpolating \\\375000_5139000_suffix (11 of 138)
> >Progress: 7%
> >thread unnamed' panicked at 'index out of bounds: the len is 604504064 but the index is 604504064',/rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\src\libcore\slice\mod.rs:2463:10
> >thread 'unnamed' panicked at 'index out of bounds: the len is 604504064 but the index is 604504064',/rustc/9fda7c2237db910e41d6a712e9a2139b352e558b\src\libcore\slice\mod.rs:2463:10

**Comment by jfprieur** [comment]
Hello again, I figured out why this was happening, am posting in case anyone else has these issues. It was caused by ridiculous scale factors and offsets in the LAS file. I corrected using las2las from lastools and everything works fine now. Am closing
