### ISSUE TITLE
Repair Stream Vector Topology - 'No such file or directory' error

### ISSUE THREAD

**Issue by ClaudiaSauro** [jblindsay/whitebox-tools#367]
Hello!

I am having issues running the repair_stream_vector_topology tool. I've been able to run many of the raster tools (ex. breach_single_cell_pits, d8_pointer, slope, etc.) with no issues (even with the same settings.json error as what you will see in the below screenshow), but for some reason I get this error when trying the repair_stream_vector_topology tool: _thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', whitebox-vector/src/shapefile/mod.rs:238:56_ 

As you can see the working directory is set to the proper location where I have all permissions (I did also test it on 2 other locations to no avail). 
![image](https://github.com/jblindsay/whitebox-tools/assets/18309744/39a84a1f-16b2-4b26-9984-77bc95bd8070)

I also tried 3 different shapefiles, which gave me the same error. 

Here is the shapefile in ArgGIS: 
![image](https://github.com/jblindsay/whitebox-tools/assets/18309744/c148d255-3a79-48c9-9fd0-b741f00820e6)

And here is the shapefile found in the directory where the code fails:
[flows.zip](https://github.com/jblindsay/whitebox-tools/files/12243223/flows.zip)

Thank you,

Claudia

**Comment by jblindsay** [comment]
This is odd. I just ran the tool on your data set, using your same parameters, in the Whitebox Runner and it worked fine. It must therefore be something in your Python script. Can you share your script in its entirety please?

<img width="447" alt="Screenshot 2023-08-02 at 13 58 03" src="https://github.com/jblindsay/whitebox-tools/assets/8441542/4a666652-da5e-4e4c-98bf-34f874992458">

**Comment by ClaudiaSauro** [comment]
[Error.zip](https://github.com/jblindsay/whitebox-tools/files/12243605/Error.zip)

Here's the JupyterLabs notebook with the basic code that produces the error. I can copy the code in a reply if that's better. Thanks!

**Comment by ClaudiaSauro** [comment]
Here is the full error with backtrace on:

./whitebox_tools --run="RepairStreamVectorTopology" --wd="/home/sauroc/Project/functions/Shapefiles/flows" --input='flows.shp' --output='flows2.shp' --dist=1 -v --compress_rasters=False

Could not create output settings.json file. WBT is likely installed somewhere without write permission.
*****************************************
* Welcome to RepairStreamVectorTopology *
* Powered by WhiteboxTools              *
* [www.whiteboxgeo.com](http://localhost:8500/user/sauroc/doc/tree/Project/functions/Shapefiles/flows/www.whiteboxgeo.com)                   *
*****************************************
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', whitebox-vector/src/shapefile/mod.rs:238:56
stack backtrace:
0:     0x7f3085910efa - <unknown>
1:     0x7f3085943fae - <unknown>
2:     0x7f308590e625 - <unknown>
3:     0x7f3085910cc5 - <unknown>
4:     0x7f308591234f - <unknown>
5:     0x7f308591208b - <unknown>
6:     0x7f3085912a59 - <unknown>
7:     0x7f30859127f9 - <unknown>
8:     0x7f30859113ac - <unknown>
9:     0x7f3085912502 - <unknown>
10:     0x7f30858c3f23 - <unknown>
11:     0x7f30858c4373 - <unknown>
12:     0x7f30858db63d - <unknown>
13:     0x7f30858d714b - <unknown>
14:     0x7f30858d006a - <unknown>
15:     0x7f30858cea8f - <unknown>
16:     0x7f30858c98b3 - <unknown>
17:     0x7f30858c5979 - <unknown>
18:     0x7f308590ad12 - <unknown>
19:     0x7f30858d5965 - <unknown>
Failure to run plugin subprocess.

**Comment by jblindsay** [comment]
I'm sorry but the attached file does not have contain a *.ipynb file that has any code in it...

<img width="181" alt="Screenshot 2023-08-02 at 14 48 23" src="https://github.com/jblindsay/whitebox-tools/assets/8441542/0c731733-cbb4-4a22-bb55-d13959d6673c">

**Comment by ClaudiaSauro** [comment]
Oops sorry about that! Here's the code:

`import pandas as pd
pd.options.display.max_columns = None
pd.options.display.max_rows = 40

pd.options.mode.chained_assignment = None 
pd.options.display.max_colwidth = 500

import plotly.graph_objects as go

import os
os.environ['USE_PYGEOS'] = '0'
import geopandas as gpd

import whitebox

wbt = whitebox.WhiteboxTools()

print(wbt.version())

print(os.listdir("/home/sauroc/Project/functions/Shapefiles/flows/"))

# Set the working directory
wbt.set_working_dir("/home/sauroc/Project/functions/Shapefiles/flows/")

os.environ['RUST_BACKTRACE'] = 'full'

wbt.repair_stream_vector_topology("flows.shp", "flows2.shp", dist="1")`

**Comment by jblindsay** [comment]
This script worked for me:

```python
import whitebox

wbt = whitebox.WhiteboxTools()
wbt.set_verbose_mode(True)
print(wbt.version())

print(os.listdir("/Users/johnlindsay/Downloads/flows/"))

# Set the working directory
wbt.set_working_dir("/Users/johnlindsay/Downloads/flows/")

os.environ['RUST_BACKTRACE'] = 'full'

wbt.repair_stream_vector_topology(i="flows.shp", output="flows2.shp", dist="1")
```

<img width="558" alt="Screenshot 2023-08-02 at 15 33 41" src="https://github.com/jblindsay/whitebox-tools/assets/8441542/a968cb25-891a-4720-b363-2d9a2e8263f3">

Could be because you didn't use the function parameter names (`i` and `output`). I'd also set verbose mode if you'd like more output from the function directly.

**Comment by brownag** [comment]
@jblindsay Could the `"No such file or directory"` error be result of no settings.json file being available to read in the install location?

@ClaudiaSauro [wrote](https://github.com/jblindsay/whitebox-tools/issues/367#issuecomment-1662760929) above (emphasis added):
> Here is the full error with backtrace on:
> 
> ./whitebox_tools --run="RepairStreamVectorTopology" --wd="/home/sauroc/Project/functions/Shapefiles/flows" --input='flows.shp' --output='flows2.shp' --dist=1 -v --compress_rasters=False
> 
>  _**Could not create output settings.json file. WBT is likely installed somewhere without write permission.**_
> 
> ...
>

**Comment by jblindsay** [comment]
@brownag Yes, I had not noticed that, but that certainly could be the case.
