### ISSUE TITLE
whitebox_workflows 'Unrecognized tool name NormalizeLidar'

### ISSUE THREAD

**Issue by ithaca-oyler** [jblindsay/whitebox-tools#395]
I am using whitebox_tools v2.3.0 and I would like to use the normalize_lidar function. However, when calling the function, I get this error:

`thread 'main' panicked at 'Unrecognized tool name NormalizeLidar.', whitebox-tools-app/src/main.rs:72:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

The help function `?wbt.normalize_lidar` does indeed show the documentation, but `print(wbt.tool_help("normalize_lidar"))` shows the same `thread main panicked at` etc. error as listed above with calling the function itself. Additionally, normalize_lidar does not appear when listing the wbt tools with the "normalize" keyword:
`print(wbt.list_tools(['normalize']).keys())`

I have confirmed I am setting the whitebox directory to the location of the binary file and the working directory to where my data is.

**Comment by jblindsay** [comment]
Hello, can I clarify are you using WhiteboxTools or Whitebox Workflows? If this is in fact an issue with Whitebox Workflows, then I believe that I have probably resolved this issue in the latest version.

**Comment by ithaca-oyler** [comment]
Hello! I'm using WhiteboxTools and the issue is within WhiteboxTools only. I have experimented with the NormalizeLidar tool with Whitebox Workflows (only to test it) and I didn't have any issues there.

**Comment by Afrancioni** [comment]
Hello @ithaca-oyler 

I just successfully ran the NormalizeLidar Tool using whiteboxTools v2.3 without any errors. I was using the WhiteboxRunner front end. 
<img width="1207" alt="Screen Shot 2024-03-11 at 7 28 10 PM" src="https://github.com/jblindsay/whitebox-tools/assets/39802080/6b653e20-6dbb-41f0-b356-58531daf857c">

Are you interacting with the tools using a front end or command line/python?

**Comment by ithaca-oyler** [comment]
I am using the command line/python

**Comment by ithaca-oyler** [comment]
Hi @Afrancioni. Interesting... I'm still getting the same errors in the command line and in my jupyter notebook. Just to confirm, was your version of the package downloaded with pip install?
![whitebox_commandline](https://github.com/jblindsay/whitebox-tools/assets/161395345/3c308631-aaa7-42af-976c-561aba5a79e3)

**Comment by ithaca-oyler** [comment]
I'm not sure if this is helpful at all, but I decided to dig into the stack trace, error messages, and explore the repo a little bit more and found that I have the same issue with _all_ of the tools in whitebox-plugins in https://github.com/jblindsay/whitebox-tools/tree/5a82f513e77cf1c74778995b5d6304dd9d9f372f/whitebox-plugins. I'm not sure if this is an installation issue with conda-forge on my end or what. Feel free to ignore this comment if it ends up being unhelpful or totally unrelated!

**Comment by Afrancioni** [comment]
Hi @ithaca-oyler 
I am using v 2.3 of WhiteboxTools downloaded from the Whitebox Geospatial website (https://www.whiteboxgeo.com/download-whiteboxtools/). I did not pip install or use conda. I am assuming you did? Would you be able to try downloading directly from our website and test if you can run the tools from command line? I am just trying to figure out where exactly your issue is.

**Comment by stephenwaltersNV5** [comment]
I would like to add I am experiencing the same issue running Conditional Evaluation through a python script. Let me know if I can provide more information or if I should start a new thread.

whitebox 2.3.1 from conda-forge.

Error
```
thread 'main' panicked at 'Unrecognized tool name ConditionalEvaluation.', whitebox-tools-app\src\main.rs:72:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Code snip
```
from whitebox import WhiteboxTools
wbt = WhiteboxTools()

wbt.conditional_evaluation(
                i=input_raster,
                output=output_raster,
                statement="value == 0",
                true=1,
                false=None,
            )
```

**Comment by ithaca-oyler** [comment]
@Afrancioni I downloaded v2.3 from the Whitebox Geospatial website and I was able to install the Rust compiler and clone the whitebox_tools repo, but I still received the same "Unrecognized tool name" error message for NormalizeLidar in both my jupyter notebook and the command line. I am able to use other lidar and raster tools, however (also both in the command line and in a jupyter notebook).

**Comment by Afrancioni** [comment]
@ithaca-oyler Can you please paste your command line call?

**Comment by ithaca-oyler** [comment]
This is the command line call I'm using:
`.\whitebox_tools.exe -r=NormalizeLidar --wd=<path to my data> -i=input.las -o=output.las --dtm=dtm.tif`

**Comment by Afrancioni** [comment]
@ithaca-oyler are you able to see the name of the tool in the tool list when you call --list_tool? Id be curious if you can run the tool using WhiteboxRunner?

**Comment by ithaca-oyler** [comment]
@Afrancioni It does not show up when --list_tool is called. It also does not appear in the list of tools available to run in the WhiteboxRunner.

**Comment by Afrancioni** [comment]
@ithaca-oyler That is very strange. I just downloaded the WBT binary from our site here https://www.whiteboxgeo.com/download-whiteboxtools/ and all tools including the NormalizeLidar tool appear in WhiteboxRunner and when I call --list_tool. I know you have downloaded WBT through conda but I am not sure how that puts WBT together.

**Comment by ithaca-oyler** [comment]
@Afrancioni Thank you for your patience during the delay in my response. I uninstalled rust and whitebox_tools and tried the download again with no success in using the normalize_lidar tool or having it show up in the WhiteboxRunner. I've attached the log from `cargo build --release`. Do you see anything unusual here? Unfortunately, I don't know anything about Rust.
[whiteboxtools_cargo_build_log.txt](https://github.com/jblindsay/whitebox-tools/files/14925196/whiteboxtools_cargo_build_log.txt)
