### ISSUE TITLE
TimeInDayLight - error when calculating local almanac

### ISSUE THREAD

**Issue by quentin-guignard-pinoncely** [jblindsay/whitebox-tools#405]
I'm trying to use the Time In Day Light tool, but it raise this error (with the QGIS pluggin and the python interface) : 
```
WhiteboxTools output:
*****************************
* Welcome to TimeInDaylight *
* Powered by WhiteboxTools *
* www.whiteboxgeo.com *
*****************************
Calculating the local almanac...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ComponentRange { name: "ordinal", minimum: 1, maximum: 365, value: 366, conditional_range: true }', whitebox-tools-app\src\tools\terrain_analysis\time_in_daylight.rs:935:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Process returned error code 101
```

When i'm looking to the script, it seems that the script is triying to acceed to the 366 day of 2023, which it not exists.

https://github.com/jblindsay/whitebox-tools/blob/master/whitebox-tools-app/src/tools/terrain_analysis/time_in_daylight.rs#L935

**Comment by wiesehahn** [comment]
I got the same error via R, it was reported here https://github.com/opengeos/whiteboxR/discussions/74

**Comment by brownag** [comment]
Copying response from end of https://github.com/opengeos/whiteboxR/discussions/74

_Originally posted by @brownag in https://github.com/opengeos/whiteboxR/discussions/74#discussioncomment-9225559_

I can confirm I get the same error on Linux. Via the R interface or via the command line. I tinkered with some of the parameters and same result.

I notice there were some changes (NaiveTime -> Time, NaiveDate -> Date) in how time is handled in this tool for WhiteboxTools v2.3: https://github.com/jblindsay/whitebox-tools/commit/4208336a1de591bf868ed26ec8d2bf1b552c9955#diff-4c6d03f9fd598a5f68bf881cd140eedc9642af3e07fa7bdc0d062f291adba587

Based on the error output `thread 'main' panicked at 'called Result::unwrap() on an Err value: ComponentRange { name: "ordinal", minimum: 1, maximum: 365, value: 366, conditional_range: true }', whitebox-tools-app\src\tools\terrain_analysis\time_in_daylight.rs:935:30` I would guess that this is an issue related to leap years. 

2024 is a leap year, 2023 is not. Previous code used 2020. It looks like the code (Line 934 in time_in_daylight.rs) might be hard-coded to use 2023, but is iterating over day of year 1 to 366. 

https://github.com/jblindsay/whitebox-tools/blob/4208336a1de591bf868ed26ec8d2bf1b552c9955/whitebox-tools-app/src/tools/terrain_analysis/time_in_daylight.rs#L934-L941
