### ISSUE TITLE
Index error when running wb_runner

### ISSUE THREAD

**Issue by TheDude005** [jblindsay/whitebox-tools#65]
I've tried to run wb_runner.py from my command line and it keeps giving me this error
jordan@jordan-Kudu-Pro:~/WhiteboxTools_linux_amd64/WBT$ sudo python3 wb_runner.py
Traceback (most recent call last):
  File "wb_runner.py", line 1321, in <module>
    main()
  File "wb_runner.py", line 1316, in main
    wbr = WbRunner(tool_name)
  File "wb_runner.py", line 767, in __init__
    self.create_widgets()
  File "wb_runner.py", line 789, in create_widgets
    self.get_tools_list()  
  File "wb_runner.py", line 1022, in get_tools_list
    self.tool_name = self.tools_list[0]
IndexError: list index out of range

I am running Ubuntu 18.04 and I have Python3.

**Comment by giswqs** [comment]
The whitebox runner works fine on my Manjaro Linux. You can try installing the whitebox Python package using `pip install whitebox`. Then use the following command to invoke wb_runner. 

```
import whitebox
whitebox.Runner()
```
![](https://wetlands.io/file/images/whitebox.png)

**Comment by TheDude005** [comment]
Yeah I tried that, it failed to find whitebox using that method.
